### ISSUE TITLE
Milestone 1 checklist

### ISSUE THREAD

**Issue by NatalieThurlby** [NatalieThurlby/plausible#1]
## Setup
- [ ] GH setup
  - [ ] milestones/issues 
  - [ ] GH actions 
    - [ ] GH actions to publish sphinx site (from gh-pages branch)
    - [ ] GH actions to update package (from main)
    - [ ] GH actions to update README (from main)
    - [ ] Pypi packaging
  - [x] License
  - [ ] README
  - [ ] all-contributors bot
  - [ ] contribution guidelines
- [ ] sphinx
  - [ ] setup
  - [ ]  basic content
    - [ ] about the project
    - [ ] about the team
    - [ ] dev roadmap
      - [ ] initial release (pypi)
      - [ ] user testing
    - [ ] installation instructions (R)
    - [ ] installation instructions (Python) 
    - [ ] quick-start
